### ISSUE TITLE
Cannot download file with apostrophe in the filename

### ISSUE THREAD

**Issue by blokeley** [blokeley/backup_dropbox#5]
```
Traceback (most recent call last):
  File "backup.py", line 257, in save_file
    fout.write(download_file(headers, member_id, metadata['path']))
  File "backup.py", line 229, in download_file
    r.raise_for_status()
  File "C:\Users\Tom Oakley\Anaconda3\lib\site-packages\requests\models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api-content.dropbox.com/1/files/auto/...
```

**Comment by blokeley** [comment]
Merged with #3
